sudo: required
dist: trusty
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper-.*$/
addons:
  firefox: "latest"
  apt:
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '8'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
after_success:
  - ./node_modules/.bin/semantic-release
after_script:
  - kill -9 $(ps aux | grep 'pm2')
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
