sudo: required
dist: trusty
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper-.*$/
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
addons:
  firefox: 'latest'
  apt:
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '8'
  - '10'
script:
  - npm test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
