notifications:
  email: false
branches:
  only:
    - master
    - dev
    - /^greenkeeper-.*$/
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
addons:
  firefox: 'latest'
  apt:
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "lts/*"
  - "node"

jobs:
  include:
    - stage: release
      node_js: "node"
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release

